In [1]:
from pathlib import Path

from typing import Any
from bob.connections.air import * 
from bob.core import *


from bob.equipment.archives.coolingcoil import ChilledWaterCoil2, ChilledWaterCoil
from bob.equipment.archives.heatingcoil import HotWaterCoil2
from bob.property import *

from bob.equipment.hvac.damper import Damper
from bob.equipment.hvac.fan import Fan
from bob.equipment.hvac.vfd import VFD
from bob.equipment.hvac.filter import Filter
from bob.equipment.hvac.airflowstation import AirFlowMonitor
from bob.connections.water import *
from bob.role import (
    Exhaust, 
    Supply,
    Return,
) 
# from bob.signal import(
#     AnalogOut,
#     AnalogIn,
#     )

#from bob.domain import *
import pandas as pd

from header import lbnl_header

#model_name = Path(__file__).stem
model_name = 'b59'
__namespace__ = ex = bind_model_namespace("ex", f"urn:ex/{model_name}/")

qudt = bind_namespace("qudt", "http://qudt.org/schema/qudt/")
quantitykind = bind_namespace("quantitykind", "http://qudt.org/vocab/quantitykind/")

lbnl_header(model_name)

dump()

# baseURI: http://data.ashrae.org/standard223/data/b59
# imports: http://data.ashrae.org/standard223/1.0/model/all

@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://data.ashrae.org/standard223/data/b59>
  a owl:Ontology ;
  rdfs:isDefinedBy <http://data.ashrae.org/standard223/data/b59> ;
  rdfs:label "b59" ;
  owl:imports <http://data.ashrae.org/standard223/1.0/model/all> .

In [3]:
class Area(QuantifiableObservableProperty):
    node_type= None
    hasUnits = qudt.FT2
    hasQuantityKind = quantitykind.Area
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

In [4]:
class Plenum(DomainSpace):
    cp1: AirBidirectionalConnectionPoint
    cp2: AirBidirectionalConnectionPoint
    supplyInlet: AirInletConnectionPoint

In [5]:
class CeilingSpace(DomainSpace):
    returnOutlet: AirOutletConnectionPoint

In [6]:
f = Fan(label = 'fan')

a = DomainSpace(label = 'a')

a2 = DomainSpace(label = 'a2')

f._nodes

con = AirConnection()
con2 = AirConnection()

a_in = InletConnectionPoint(a)

f >> con >> a_in

a_b = BidirectionalConnectionPoint(a)

a2_b = BidirectionalConnectionPoint(a2)

# a_b >> con >> a_b
# a2_b >> con >> a2_b

In [7]:
f.airOutlet >> a_b

In [8]:
f.airOutlet >> con2 >> a2_b

In [9]:
dump()

@prefix ex: <urn:ex/b59/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix s223: <http://data.ashrae.org/standard223#> .
ex:00001 a s223:Connectable,
        s223:Equipment,
        s223:Fan ;
    rdfs:label "fan" ;
    s223:airInlet ex:00002 ;
    s223:airOutlet ex:00003 ;
    s223:connectedThrough ex:00006,
        ex:00007,
        ex:00011 ;
    s223:connectedTo ex:00004 ;
    s223:hasConnectionPoint ex:00002,
        ex:00003 .
ex:00002 a s223:InletConnectionPoint ;
    rdfs:label "fan.airInlet" ;
    s223:hasDirection s223:Direction-Inlet ;
    s223:hasMedium s223:Medium-Air ;
    s223:isConnectionPointOf ex:00001 .
ex:00003 a s223:OutletConnectionPoint ;
    rdfs:label "fan.airOutlet" ;
    s223:hasDirection s223:Direction-Outlet ;
    s223:hasMedium s223:Medium-Air ;
    s223:isConnectionPointOf ex:00001 .
ex:00004 a s223:Connectable,
        s223:DomainSpace ;
    rdfs:label "a" ;
    s223:connectedFrom ex:00001 ;
    s223:connectedThrough ex:00006,
        ex:00011 ;
    s223:hasConnectionPoint ex:00008,
        ex:00009 .
ex:00005 a s223:Connectable,
        s223:DomainSpace ;
    rdfs:label "a2" ;
    s223:connectedThrough ex:00007 ;
    s223:hasConnectionPoint ex:00010 .
ex:00006 a s223:Connection ;
    s223:connectsAt ex:00003,
        ex:00008 ;
    s223:connectsFrom ex:00001 ;
    s223:connectsTo ex:00004 ;
    s223:hasMedium s223:Medium-Air .
ex:00007 a s223:Connection ;
    s223:connectsAt ex:00003,
        ex:00010 ;
    s223:connectsFrom ex:00001 ;
    s223:connectsTo ex:00005 ;
    s223:hasMedium s223:Medium-Air .
ex:00008 a s223:InletConnectionPoint ;
    s223:hasDirection s223:Direction-Inlet ;
    s223:isConnectionPointOf ex:00004 .
ex:00009 a s223:BidirectionalConnectionPoint ;
    s223:hasDirection s223:Direction-Bidirectional ;
    s223:isConnectionPointOf ex:00004 .
ex:00010 a s223:BidirectionalConnectionPoint ;
    s223:hasDirection s223:Direction-Bidirectional ;
    s223:isConnectionPointOf ex:00005 .
ex:00011 a s223:Connection ;
    s223:connectsAt ex:00003,
        ex:00009 ;
    s223:connectsFrom ex:00001 ;
    s223:connectsTo ex:00004 ;
    s223:hasMedium s223:Medium-Air .

In [10]:
clear()

In [11]:
clear()

In [33]:
lighting_spaces_df=pd.read_csv('~/Desktop/223p/LP/b59_lighting_spaces_v4.csv')
lighting_sys_df=pd.read_csv('~/Desktop/223p/LP/b59_lighting_v2.csv')
lighting_spaces_df = lighting_spaces_df.drop_duplicates(subset = ['Room_Number'], keep = 'last')
Floor3 = PhysicalSpace(label='Floor_3')
Floor4 = PhysicalSpace(label='Floor_4')

In [34]:
lighting_spaces_df = lighting_spaces_df.drop_duplicates(subset = ['Room_Number'], keep = 'last')

In [35]:
#dropped_ind = set(lighting_spaces_df.index)-(set(lighting_spaces_df_c.index))

In [36]:
lighting_spaces_df#.loc[lighting_spaces_df['Room_Number'] == '3070G']

,Room_Number,Corridor,LightingArea,SquareFootage,New Area Name,Notes,new_notes,Floor,RTU
0,3096,NaN,NaN,476.21,NaN,Stairwell,Stair,3.0,4.0
1,3070G,NaN,OpenOffice_3217,61.79,Open Office 3217,NaN,Open Office,3.0,4.0
2,3070H,NaN,OpenOffice_3217,54.44,Open Office 3217,NaN,Open Office,3.0,4.0
3,3070F,NaN,OpenOffice_3217,61.18,Open Office 3217,NaN,Open Office,3.0,4.0
4,3070E,NaN,OpenOffice_3217,53.18,Open Office 3217,NaN,Open Office,3.0,4.0
...,...,...,...,...,...,...,...,...,...
483,4019H,NaN,OpenOffice_4203,22.42,Open Office 4203,NaN,Open Office,4.0,1.0
484,4019J,NaN,OpenOffice_4203,22.42,Open Office 4203,NaN,Open Office,4.0,1.0
485,4019K,NaN,OpenOffice_4203,22.42,Open Office 4203,NaN,Open Office,4.0,1.0
486,4019N,NaN,OpenOffice_4203,456.15,Open Office 4203,NaN,Open Office,4.0,2.0
487,4019P,NaN,OpenOffice_4203,222.18,Open Office 4203,NaN,Open Office,4.0,2.0

In [37]:
all_rooms = {}
#Creating every room and containing them in the 3rd or 4th floor. This doesn't include more details about the space or the few lighting domain subspaces
for i, row in lighting_spaces_df.iterrows():
    rm = str(row.Room_Number)
    if str(rm)[0].isdigit():
        all_rooms[rm] = PhysicalSpace(label='room_'+rm)
        #rm_sqft = Area(row.SquareFootage)
        #all_rooms[rm].add_property(rm_sqft)
        if pd.isna(row['New Area Name']):
            continue
        if ('.' in row['New Area Name']):
            continue
        if int(rm[0]) == 3:
            Floor3 > all_rooms[rm]
        if int(rm[0]) == 4:
            Floor4 > all_rooms[rm]

In [16]:
ftemp = Fan(label = 'a')

In [17]:
ftemp._nodes

{'hasRole': bob.core.Role,
 'hasPhysicalLocation': bob.core.PhysicalSpace,
 'airInlet': bob.connections.air.AirInletConnectionPoint,
 'airOutlet': bob.connections.air.AirOutletConnectionPoint,
 'staticPressure': bob.properties.force.Pressure,
 'amps': bob.properties.electricity.Amps,
 'rpm': bob.properties.ratio.RPM,
 'hp': bob.properties.force.HP,
 'kW': bob.properties.electricity.ElectricPowerkW,
 'powerFactor': bob.properties.electricity.PowerFactor,
 'hasOnOffStatus': bob.core.PropertyReference,
 'hasOnOffCommand': bob.core.PropertyReference}

In [18]:
clear()

In [19]:
zone_df=pd.read_csv('/Users/lazlopaul/Desktop/brick/LPbricktesting/b59_UFT_ahu_rm.csv')
r_mat = {} #rtu matrix
r_mat['rtus'] ={} #rooftop units
for i in range(1,5):
    r_mat[i] = RooftopUnit(label="RTU_"+str(i))

NameError: name 'RooftopUnit' is not defined

In [20]:
zone_df

,Unnamed: 0,Floor_Number,Rooms,UFT,ahuRef,hasCO2
0,0,3,"3042B, 3042C",G-25,2,1.0
1,1,3,3070,G-6,4,1.0
2,2,4,"4019B, 4019C, 4019E, 4019F, 4019G, 4019H, 401...",2-22,1,0.0
3,3,4,"4020, 4021",2-10,3,0.0
4,4,4,"4022B, 4022C, 4022F, 4022G",2-5,4,0.0
5,5,3,"3022, 3033, 3024",G-20,1,0.0
6,6,3,"3034, 3026, 3027A, 3027D",G-23,1,0.0
7,7,4,4019N,2-23,2,0.0
8,8,3,"3070, 3069, 3069A, 3069D",G-7,4,0.0
9,9,3,"3025, 3026, 3026A, 3026D",G-22,1,0.0
10,10,4,4111,2-13A,3,0.0
11,11,3,"3049, 3050",G-11,2,0.0
12,12,4,"4016, 4019A",2-21,1,0.0
13,13,4,"4011D, 4011H, 4012, 4013, 4013D, 4013H",2-16,1,0.0
14,14,3,"3010, 3010C, 3010D, 3013",G-16,2,0.0
15,15,4,"4101, 4102",2-25,3,1.0
16,16,4,"4016P, 4016Q, 4016R, 4016S, 4016T",2-19,1,0.0
17,17,3,"3059, 3054, 3054A, 3054D",G-9,3,0.0
18,18,4,4207,2-1,4,0.0
19,19,3,"3018, 3021, 3021B",G-18,1,0.0
20,20,4,4016,2-20,1,1.0
21,21,4,4021P,2-7,4,0.0
22,22,4,"4018, 4019",2-11,2,0.0
23,23,3,3102,G-4A,2,0.0
24,24,3,3071A,G-1,4,0.0
25,25,4,4111,2-13B,3,0.0
26,26,3,3049,G-12,2,1.0
27,27,4,"4010, 4010C, 4011",2-15,2,0.0
28,28,4,"4014, 4015, 4320",2-17,1,0.0
29,29,3,"3042, 3034, 3034A, 3034D",G-24,2,0.0
30,30,3,"3070B, 3070C, 3070F, 3070G, 3299",G-5,4,0.0
31,31,3,"3022F, 3022G",G-19,1,0.0
32,32,4,"4016L, 4016M, 4016N",2-18,1,0.0
33,33,4,4107,2-14B,2,0.0
34,34,4,"4028, 4028B, 4028C, 4029, 4030",2-3,3,0.0
35,35,3,"3051, 3052",G-10,3,0.0
36,36,4,4110,2-13D,2,0.0
37,37,3,3104,G-15,3,1.0
38,38,3,"3074, 3074B, 3074C, 3075, 3076",G-3,3,0.0
39,39,3,"3069, 3060, 3060A, 3060D",G-8,4,0.0
40,40,4,4103,2-4A,2,0.0
41,41,3,3106,G-13A,3,0.0
42,42,3,3106,G-13B,3,0.0
43,43,4,4018,2-12,2,1.0
44,44,4,4022,2-6,4,0.0
45,45,3,3025,G-21,1,1.0
46,46,3,"3012B, 3012C , 3012D, 3012E, 3014, 3017, 3321...",G-17,1,0.0
47,47,4,"4021A, 4021B, 4021C, 4021D, 4021E",2-9,3,0.0
48,48,3,3101,G-14,3,0.0
49,49,4,4019P,2-24,2,1.0
50,50,3,"3071, 3072, 3072B, 3072C, 3073",G-2,4,0.0
51,51,4,"4025, 4026, 4026B, 4026C, 4027",2-2,4,0.0
52,52,4,4107,2-14A,2,1.0
53,53,4,"4021P, 4021F, 4021G, 4021H, 4021J, 4021K, 402...",2-8,4,0.0

In [21]:
clear()

In [22]:
plenum={} # plenum[Floor][RTU]
ceiling_space = {}
core_zones = {}
for floor in range(3,5):
    plenum[floor] = {}
    ceiling_space[floor] = {}
    core_zones[floor] = {}
    for rtu in range(1,5):
        # creating plenums for each RTU and connecting them to each other
        core_zones[floor][rtu] = Zone(label="Floor_{}.RTU_{}.CoreZone".format(floor,rtu))
        plenum[floor][rtu] = Plenum(label="Floor_{}.RTU_{}.Plenum".format(floor,rtu))
        ceiling_space[floor][rtu] = CeilingSpace(label="Floor_{}.RTU_{}.Ceiling".format(floor,rtu))
        if rtu > 1:
            plenum[floor][rtu-1].cp2 >> plenum[floor][rtu].cp1
            plenum[floor][rtu-1].cp2 << plenum[floor][rtu].cp1
        # connecting plenums to RTU
        r_mat[rtu].supplyAirOutlet >> plenum[floor][rtu].supplyInlet
        r_mat[rtu].returnAirInlet << ceiling_space[floor][rtu].returnOutlet
        r_mat[rtu].servesZone = core_zones[floor][rtu]

KeyError: 1

In [23]:
dir(r_mat[rtu].serves_zone())

KeyError: 1

In [24]:
dir(r_mat[ahu_ind]._contents)

NameError: name 'ahu_ind' is not defined

In [25]:
uft_rooms = []
ufts = {}
uftzones = {}
HVACrooms = {}
for i, row in zone_df.iterrows(): #iterating through UFTs
    rooms = [rm.strip() for rm in row['Rooms'].split(',')] #getting list of rooms for UFT
    ufts[row['UFT']] = UFT(label = row['UFT']) #creating UFT with points, as well as zone and zone sensors
    #creating normal UFT's for each zone (not sure how to determine the different UFTs at this moment)
    uftzones[row['UFT']] = UFTZone(label = row['UFT']+'.zone')
    ufts[row['UFT']].servesZone = uftzones[row['UFT']]
    if bool(row['hasCO2']): #some zones have a CO2 concentration
        co2conc = CO2Concentration()
        uftzones[row['UFT']].add_property(co2conc)
    floor_ind = row['Floor_Number']
    ahu_ind = row['ahuRef']
    r_mat[ahu_ind].servesZone = uftzones[row['UFT']]
    plen_cp = AirOutletConnectionPoint(
        plenum[floor_ind][ahu_ind]
    )
    plen_cp >> uft.supplyAirInlet
              
    # IF A AND D ARE LISTED IN ROOMS, ADDING B AND C. Below is stupid and convoluted
    if ('A' in ''.join(rooms)) & ('D' in ''.join(rooms)) & ~('B' in ''.join(rooms)) & ~('C' in ''.join(rooms)):
        rm_base = [rm_base for rm_base in rooms if 'A' in rm_base][0][:-1]
        rooms = rooms + [rm_base+'B', rm_base+'C']
    for j,room_label in enumerate(rooms):
        uft_rooms.append(room_label)
        HVACrooms[room_label] = DomainSpace(label=room_label) # I am not sure yet how DomainSpace and Physical Space should Interact here. Just making physical space contain a domain space.
        HVACrooms[room_label].hasDomain = HVAC
        if room_label in all_rooms.values():
            all_rooms[room_label] > HVACrooms[room_label]
        uftzones[row['UFT']] > HVACrooms[room_label] 
        room_supply_cp = AirInletConnectionPoint(HVACroom, label=HVACroom.label + ".supplyAir")
        room_return_cp = AirOutletConnectionPoint(HVACroom, label=HVACroom.label + ".returnAir")
        ufts[row['UFT']].supplyAirOutlet >> room_supply_cp
        ceil_cp = AirInletConnectionPoint(
            ceiling_space[floor_ind][ahu_ind]
        )
        room_return_cp >> ceil_cp

NameError: name 'UFT' is not defined

In [26]:
core_spaces = lighting_spaces_df.loc[~lighting_spaces_df['Room_Number'].isin(uft_rooms)].copy()

In [27]:
core_spaces = core_spaces.loc[core_spaces['Notes'].isna()]

In [28]:
core_spaces.columns

Index(['Room_Number', 'Corridor', 'LightingArea', 'SquareFootage',
       'New Area Name', 'Notes', 'new_notes', 'Floor', 'RTU'],
      dtype='object')

In [29]:
for i, row in core_spaces.iterrows():
    HVACroom = DomainSpace(label = row.Room_Number)
    HVACroom.hasDomain = HVAC
    core_zone[int(row.Floor)][int(row.RTU)] > HVACroom

NameError: name 'core_zone' is not defined

In [30]:
for i,zn in enumerate(zone_df['Rooms']): #iterating through UFTs
    rooms = [rm.strip() for rm in zn.split(',')] #getting list of rooms for UFT

    uft = UFT(label = zone_df.iloc[i]['UFT']) #creating UFT with points, as well as zone and zone sensors
    #creating normal UFT's for each zone (not sure how to determine the different UFTs at this moment)
    zone = UFTZone(label = zone_df.iloc[i]['UFT'])
    supply_junction = Junction(label = zone_df.iloc[i]['UFT']+'.junction')
    zone.supplyAir.mapsTo = supply_junction
    uft.servesZone = zone
    if bool(zone_df.iloc[i]['hasCO2']): #some zones have a CO2 concentration
        co2conc = CO2Concentration()
        zone.add_property(co2conc)

    if zone_df.iloc[i]['Floor_Number'] == 3: #plenum 3 air goes into UFT, and is returned to return duct from zone
        p3.link_to(supply_junction)
    elif zone_df.iloc[i]['Floor_Number'] == 4:
        p4.link_to(supply_junction)
    else:
        raise ValueError("no valid floor number")
    # ZONE FED BY UFT  
    # IF A AND D ARE LISTED IN ROOMS, ADDING B AND C. Below is stupid and convoluted
    if ('A' in ''.join(rooms)) & ('D' in ''.join(rooms)) & ~('B' in ''.join(rooms)) & ~('C' in ''.join(rooms)):
        rm_base = [rm_base for rm_base in rooms if 'A' in rm_base][0][:-1]
        rooms = rooms + [rm_base+'B', rm_base+'C']
    for j,room_label in enumerate(rooms):
        HVACroom = DomainSpace(label=room_label) # I am not sure yet how DomainSpace and Physical Space should Interact here. Just making physical space contain a domain space.
        HVACroom.hasDomain = HVAC
        if room_label in all_rooms.values():
            all_rooms[room_label] > HVACroom
        zone > HVACroom #This should be encloses rather than contains now I think
        room_supply_cp = AirInletConnectionPoint(HVACroom, label=HVACroom.label + ".supplyAir")
        room_return_cp = AirOutletConnectionPoint(HVACroom, label=HVACroom.label + ".returnAir")
        supply_junction.link_to(room_supply_cp)

        if zone_df.iloc[i]['Floor_Number'] == 3:
            r_mat['rtu_return_junction_F3'][zone_df.iloc[i]['ahuRef']].connect_to(room_return_cp)#getting the return junction for the correct floor and ahu
        elif zone_df.iloc[i]['Floor_Number'] == 4:
            r_mat['rtu_return_junction_F4'][zone_df.iloc[i]['ahuRef']].connect_to(room_return_cp)
        else:
            raise ValueError("no valid floor number")

            #should the rooms have their own domain spaces, or should they be contained by a single domain space. How do I do air inlet if I have multiple domain spaces in zone, can't map like in HVACZone1

            #Domain space is bigger than room. Currently physical spaces enclose domain spaces, not vice versa. Here the domainspace is bigger than all of the sensible physical spaces.

NameError: name 'UFT' is not defined

In [31]:
zone_df=pd.read_csv('/Users/lazlopaul/Desktop/brick/LPbricktesting/b59_UFT_ahu_rm.csv')
r_mat = {} #rtu matrix
r_mat['rtus'] ={} #rooftop units
for i in range(1,5):
    r_mat['rtus'][i] = RooftopUnit(label="RTU_"+str(i))
    r_mat['rtu_supply'][i] = Segment(label='RTU_'+str(i)+'.Supply_Duct')
    #r_mat['rtu_supply'][i].hasRole = Supply
    r_mat['rtu_return'][i] = Segment(label='RTU_'+str(i)+'.Return_Duct') # not sure if this is strictly needed
    #r_mat['rtu_return'][i].hasRole = Return
    #not sure if there should be junction or individual connection points for each RTU
    # NOT SURE I"M USING SEGMENTS OR LNX CORRECTLY 
    # r_mat['rtu_return'][i].link_to(r_mat['rtus'][i].returnAirInlet.mapsTo) #I AM USING THE MAPS TO BECAUSE THATS WHAT WORKS FOR JUNCTIONS, NOT SURE IF I"M MISSING SOMETHING
    # pj = Junction(label='PlenumJunction' + ".RTU_"+str(i) + ".supplyInlet")
    # r_mat['rtu_supply'][i].link_to(r_mat['rtus'][i].supplyAirOutlet.mapsTo)
    # r_mat['rtu_supply'][i].link_to(pj)
    # pj.link_to(p3)
    # pj.link_to(p4)
    r_mat['rtus'][i].supplyAirOutlet.mapsTo >> p3
    r_mat['rtus'][i].supplyAirOutlet.mapsTo >> p4
#I would imagine that it'd be good to have plenum  as a subclass for usability. 
#It seems that the plenum is more like a junction than a segment
#Having difficulty connecting a segment to a system connection point. 
    r_mat['rtu_return_zone_F3'][i] = ReturnZone(label = 'RTU_'+str(i)+'.Floor_3.Return_Zone')
    r_mat['rtu_return_zone_F4'][i] = ReturnZone(label = 'RTU_'+str(i)+'.Floor_4.Return_Zone')
    r_mat['rtu_return_junction_F3'][i] = Junction(label = 'RTU_'+str(i)+'.Floor_3.Return_Vent')
    r_mat['rtu_return_junction_F4'][i] = Junction(label = 'RTU_'+str(i)+'.Floor_4.Return_Vent') 
    r_mat['rtu_return_zone_F3'][i].returnAirInlet.mapsTo = r_mat['rtu_return_junction_F3'][i]
    r_mat['rtu_return_zone_F4'][i].returnAirInlet.mapsTo = r_mat['rtu_return_junction_F4'][i]
    #This isn't as parallel construction to the UFT because there is not a junction both at the border of the system and the zone
    r_mat['rtu_return_splitter'][i] = Junction(label = 'RTU_'+str(i)+'.Return_Split') 
    r_mat['rtu_return_splitter'][i].link_to(r_mat['rtu_return_junction_F3'][i])
    r_mat['rtu_return_splitter'][i].link_to(r_mat['rtu_return_junction_F4'][i])
    r_mat['rtu_return_splitter'][i].link_to(r_mat['rtu_return'][i])

for i,zn in enumerate(zone_df['Rooms']): #iterating through UFTs
    rooms = [rm.strip() for rm in zn.split(',')] #getting list of rooms for UFT

    uft = UFT(label = zone_df.iloc[i]['UFT']) #creating UFT with points, as well as zone and zone sensors
    #creating normal UFT's for each zone (not sure how to determine the different UFTs at this moment)
    zone = UFTZone(label = zone_df.iloc[i]['UFT'])
    supply_junction = Junction(label = zone_df.iloc[i]['UFT']+'.junction')
    zone.supplyAir.mapsTo = supply_junction
    uft.servesZone = zone
    if bool(zone_df.iloc[i]['hasCO2']): #some zones have a CO2 concentration
        co2conc = CO2Concentration()
        zone.add_property(co2conc)

    if zone_df.iloc[i]['Floor_Number'] == 3: #plenum 3 air goes into UFT, and is returned to return duct from zone
        p3.link_to(supply_junction)
    elif zone_df.iloc[i]['Floor_Number'] == 4:
        p4.link_to(supply_junction)
    else:
        raise ValueError("no valid floor number")
    # ZONE FED BY UFT  
    # IF A AND D ARE LISTED IN ROOMS, ADDING B AND C. Below is stupid and convoluted
    if ('A' in ''.join(rooms)) & ('D' in ''.join(rooms)) & ~('B' in ''.join(rooms)) & ~('C' in ''.join(rooms)):
        rm_base = [rm_base for rm_base in rooms if 'A' in rm_base][0][:-1]
        rooms = rooms + [rm_base+'B', rm_base+'C']
    for j,room_label in enumerate(rooms):
        HVACroom = DomainSpace(label=room_label) # I am not sure yet how DomainSpace and Physical Space should Interact here. Just making physical space contain a domain space.
        HVACroom.hasDomain = HVAC
        if room_label in all_rooms.values():
            all_rooms[room_label] > HVACroom
        zone > HVACroom #This should be encloses rather than contains now I think
        room_supply_cp = AirInletConnectionPoint(HVACroom, label=HVACroom.label + ".supplyAir")
        room_return_cp = AirOutletConnectionPoint(HVACroom, label=HVACroom.label + ".returnAir")
        supply_junction.link_to(room_supply_cp)

        if zone_df.iloc[i]['Floor_Number'] == 3:
            r_mat['rtu_return_junction_F3'][zone_df.iloc[i]['ahuRef']].connect_to(room_return_cp)#getting the return junction for the correct floor and ahu
        elif zone_df.iloc[i]['Floor_Number'] == 4:
            r_mat['rtu_return_junction_F4'][zone_df.iloc[i]['ahuRef']].connect_to(room_return_cp)
        else:
            raise ValueError("no valid floor number")

            #should the rooms have their own domain spaces, or should they be contained by a single domain space. How do I do air inlet if I have multiple domain spaces in zone, can't map like in HVACZone1

            #Domain space is bigger than room. Currently physical spaces enclose domain spaces, not vice versa. Here the domainspace is bigger than all of the sensible physical spaces. 

#Instantiating Water System, this may prompt a lot of questions for s223 strike team
CWS = CoolingWaterSystem(label = 'Cooling_Water_System')
CTS = CoolingTowerSystem(label = 'Cooling_Tower_System')
CWS.CWReturn << CTS.waterOutlet #check this connection
SSF = SSFSystem(CTS, label = 'SSF_System')
#Not further instantiating water connections (connecting chilled water to coils) because I don't understand the nature of those connections
#No information on boiler, so not included at this time

# ADDING CORE ZONES

NameError: name 'RooftopUnit' is not defined

In [32]:

#Air = Substance(node_iri=s223.Air)
class CoolingSetpoint(QuantifiableActuatableProperty): #NOT IN STANDARD
    hasQuantityKind = quantitykind.Temperature
    hasUnits = qudt.DEG_F
    node_type: URIRef = s223.CoolingSetpoint
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
class HeatingSetpoint(QuantifiableActuatableProperty): #NOT IN STANDARD
    hasQuantityKind = quantitykind.Temperature
    hasUnits = qudt.DEG_F
    node_type: URIRef = s223.HeatingSetpoint
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
class Temperature(QuantifiableObservableProperty): #NOT IN STANDARD
    hasQuantityKind = quantitykind.Temperature
    hasUnits = qudt.DEG_F
    node_type: URIRef = s223.Temperature
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

class TemperatureSensor(Equipment):
    node_type: URIRef = s223.Sensor
    temperature = QuantifiableObservableProperty  #AnalogIn This results in the turtle file having temperature listed as a property and listed plainly. 
    temperature.hasQuantityKind = quantitykind.Temperature
    temperature.hasUnits = qudt.DEG_F
    hasObservationLocation: Node #  Set[Union[Equipment, Connection]] I get unknown annotation for this
     #is this how I would add measurement location? should it be a property instead? How would I add it as a property? #Zone should be included in measurement locations
class RTUFan(Fan):
    node_type= None
    speedSetpoint = QuantifiableActuatableProperty
    speedSetpoint.hasUnits = qudt.PERCENT
    speedSetpoint.hasQuantityKind = qudt.Speed
    #not sure if it should be qudt.Speed AngularFrequency, something else?
    power = QuantifiableObservableProperty
    power.hasQuantityKind = quantitykind.ElectricPower 
    power.hasUnits = qudt.kiloW
    speedFeedback = QuantifiableObservableProperty #also look up more info on this
    speedFeedback.hasQuantityKind = quantitykind.Frequency
    speedFeedback.hasUnits = qudt.HZ
    vfd_start_stop = ActuatableProperty #Should add categorical (enumerated) to this later 
    airFlow = QuantifiableObservableProperty #need to look up units
    airFlow.hasQuantityKind = quantitykind.VolumeFlowRate
    airFlow.hasUnits = qudt.FT3_PER_MIN #does this have to be dashes????
class RTUDamper(Damper):
    node_type= None
    #position = Analog Out from hvac.py. Exhaust Air Damper doesn't have a position command in the Haystack model. Here I am adding it
    positionFeedback = QuantifiableObservableProperty
    #positionFeedback.hasQuantityKind = nothing good for position
    positionFeedback.hasUnits = quantitykind.PERCENT
class RTUChilledWaterCoil(ChilledWaterCoil):
    node_type= None
    compressor1Status: ObservableProperty
    compressor2Status: ObservableProperty
    Compressor1Cooling: ActuatableProperty #not sure what more information the cooling commands should have
    Compressor2Cooling: ActuatableProperty 

    #diagram has sensors, but this is not in haystack... Not sure if I want to do the below. Sensors are shown in the diagram so I am including them, like the other Equipment
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        ts1 = TemperatureSensor(label = self.label + '.in_temperature_sensor') 
        ts2 = TemperatureSensor(label = self.label + '.out_temperature_sensor')

        ts1 % self.chilledWaterInlet
        ts2 % self.chilledWaterOutlet
class PressureSensor(Equipment): #should have just made a sensor class probs #WILL NEED TO HANDLE DIFFERENTIAL PRESSURE DIFFERENTLY
    node_type: URIRef = s223.Sensor
    pressure = QuantifiableObservableProperty  #AnalogIn This results in the turtle file having temperature listed as a property and listed plainly. 
    pressure.hasQuantityKind = quantitykind.StaticPressure #QUDT doesn't seem to have differential pressure quantity kind
    pressure.hasUnits = qudt.IN_H2O
    #check what unit
    hasObservationLocation: Node # FOR DIFFERENTIAL PRESSURE, should probably maybe make a new sensor that measures connection points around Equipment
class RooftopUnit(System):
    node_type= None #missing some of the points in the haystack model that are not attached to equipment or shown in the diagram. (duct heat gain, outside air flow, economizer enable status, outside air temperature)
    returnAirInlet: AirInletSystemConnectionPoint
    outsideAirInlet: AirInletSystemConnectionPoint
    supplyAirOutlet: AirOutletSystemConnectionPoint
    exhaustAirOutlet: AirOutletSystemConnectionPoint

    #should I put the basic command and feedback in the class here?
    
    #deciding not to use self, if I need ot access the RTU outside of this class it'd probably be good to have, but will I?
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)

        mixed_air_damper = RTUDamper(label=self.label + ".mixed_air_damper")
        self > mixed_air_damper
        mixed_air = AirConnection(label=self.label + ".mixed_air")

        self.sensor = TemperatureSensor(label=self.label + '.MA_temp_sensor')
        self >self.sensor
        self.sensor % mixed_air#This seems weird, but I kind of like it. You're measuring the mixed air connection 
       
        return_fan = RTUFan(label=self.label + ".return_fan")
        self >return_fan
        return_fan.hasRole = Return
        self.returnAirInlet.mapsTo = return_fan.airInlet
        return_air = AirConnection(label=self.label + ".return_air")
        return_fan >> return_air
        ra_temp = TemperatureSensor(label=self.label+".RA_temp_sensor")
        self > ra_temp
        ra_temp % return_air

        ra_pres = PressureSensor(label=self.label+".RA_static_pressure")
        self > ra_pres
        ra_pres % return_air

        #making backdraft damper (exhaust damper) and connecting it
        ea_damper= RTUDamper(label=self.label + ".exhaust_air_damper")
        self >ea_damper
        ea_damper.hasRole = Exhaust
        return_air>>ea_damper   
        self.exhaustAirOutlet.mapsTo = ea_damper.airOutlet

        oa_damper = RTUDamper(label=self.label + ".outside_air_damper")
        self >oa_damper
        self.outsideAirInlet.mapsTo = oa_damper.airInlet
        #connecting damper directly to flow station, not indicating OA air
        oa_flow_station = AirFlowMonitor(label=self.label + ".outside_air_flow_station")
        self >oa_flow_station
        oa_damper >> oa_flow_station >> mixed_air

        pre_filter = Filter(label=self.label + '.pre_filter')
        self >pre_filter
        pf_press = PressureSensor(label=self.label + 'PF_differential_pressure') # Do I need a different pressure sensor
        self >pf_press
        pf_press % pre_filter        

        #filter has one connection, making new air to connect to bypass and coil
        pre_filtered_air = AirConnection(label=self.label + ".pre_filtered_air")
        mixed_air >> pre_filter >> pre_filtered_air

        bp_damper = RTUDamper(label=self.label + ".bypass_damper")
        self >bp_damper
        #schematic has an iso valve but I don't think that's what chilledWaterCoil2 is talking about
        cwc = RTUChilledWaterCoil(label=self.label + ".chilled_water_coil")
        self >cwc
        #both the damper and air need to go into a filter, air as a medium?
        chilled_air = AirConnection(label=self.label+".chilled_air")
        pre_filtered_air>>bp_damper>>chilled_air
        pre_filtered_air>>cwc>>chilled_air

        #connect via air connections or create junctions/segments: Why create junctions when I can make multiple things connect too or from an AirConnection?

        final_filter = Filter(label=self.label + '.final_filter')
        self >final_filter
        ff_press = PressureSensor(label = self.label + '.FF_differential_pressure')
        self >ff_press
        ff_press % final_filter

        supply_fan = RTUFan(label=self.label + '.supply_fan')
        self >supply_fan
        supply_fan.hasRole = Supply
        chilled_air>>final_filter>>supply_fan

        supply_air = AirConnection(label = self.label + '.supply_air')
        sa_press = PressureSensor(label = self.label + '.SA_static_pressure')
        self > sa_press
        sa_press % supply_air
        sa_temp = TemperatureSensor(label = self.label + '.SA_temperature')
        self >sa_temp
        sa_temp % supply_air

               
        self.iso_damper = Damper(label=self.label + '.iso_damper')
        self >self.iso_damper
        supply_fan >> self.iso_damper

        self.supplyAirOutlet.mapsTo = self.iso_damper.airOutlet

#Should a plenum be a segment or is system correct?? 
class UFPlenum(DomainSpace):
    node_type= s223.Plenum #line 717 making sure that the connection doesn't already exist uses the substance. This means I can't make a new subclass with the same substance but different points. 
    staticPressure=QuantifiableObservableProperty #Can connections have points? This doesn't seem to work the same way as Equipment.
    staticPressure.hasQuantityKind = quantitykind.StaticPressure
    staticPressure.hasUnits = qudt.IN_H2O
    hasDomain = HVAC
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
    #HAVE TO DO SOMETHING WITH MEDIUM

    # SupplyInlet: AirInletConnectionPoint
    # SupplyOutlet: AirOutletConnectionPoint
    # ReturnInlet: AirInletConnectionPoint
    # ReturnOutlet: AirOutletConnectionPoint

    #Underfloor plenum, making it a space even though it could be many things
    #hasDomain = HVAC
    #hasSubstance = Air
class UFT_Fan(Fan):
    node_type= None
    speed_ctrl = QuantifiableActuatableProperty
    speed_ctrl.hasUnits = qudt.PERCENT
    speed_ctrl.hasQuantityKind = qudt.Speed #WHAT additional detail should I add to these points??
    #fan_amps = AnalogIn
class HotWaterCoilUFT(HotWaterCoil2):
    node_type: URIRef = s223.HeatingCoil
    pass #HotWaterCoil2 has everything I need
class UFT(System): #Underfloor Fan Terminal Unit
    node_type=None
    supplyAirInlet: AirInletSystemConnectionPoint
    supplyAirOutlet: AirOutletSystemConnectionPoint
    staticPressure=QuantifiableObservableProperty #Can connections have points? This doesn't seem to work the same way as Equipment.
    staticPressure.hasQuantityKind = quantitykind.StaticPressure
    staticPressure.hasUnits = qudt.IN_H2O
    airFlow = QuantifiableObservableProperty #need to look up units
    airFlow.hasQuantityKind = quantitykind.VolumeFlowRate
    airFlow.hasUnits = qudt.FT3_PER_MIN #does it have to be dashes: FT3-PER-MIN????
    #reheat valve command in hotWaterCoil2 in hvac.py. It is analog in there
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        supply_fan = UFT_Fan(label=self.label + ".supply_fan")
        self>supply_fan
        supply_fan.hasRole = Supply
        self.supplyAirInlet.mapsTo = supply_fan.airInlet
        hw_coil = HotWaterCoilUFT(label=self.label+".hw_coil")           #problem using HotWaterCoil2, mapping a system connection point to a system connection point that maps to a Equipment connection point
        supply_fan >> hw_coil
        self>hw_coil
        self.supplyAirOutlet.mapsTo = hw_coil.hot_water_coil.airOutlet #have to map system to the Equipment connection point in the subsystem, does this make sense?    
class UFTZone(Zone): #adding CO2 point in instantiation #Could use HVACZone1 but space is not declared as self.space. What is the more streamlined way of doing this?
    node_type= None
    supplyAir: AirInletZoneConnectionPoint
    heating_setpoint = HeatingSetpoint
    cooling_setpoint = CoolingSetpoint
    temperature = Temperature
    hasDomain = HVAC
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        #temperature_sensor = TemperatureSensor(label = self.label + '.temperature_sensor') #this will be for cerc temploggers.
        #temperature_sensor % self  #not sure if I even wan't it to measure zone or space
        # print(self)
        # self.space = DomainSpace(label=self.label + ".space")
        # self.space.hasDomain = HVAC

        # self.supplyAir.mapsTo = AirInletConnectionPoint(
        #     self.space, label=self.label + ".space.supplyAir"
        # )
        # self.returnAir.mapsTo = AirOutletConnectionPoint(
        #     self.space, label=self.label + ".space.returnAir"
        # )
        # self>self.space

class CO2Concentration(QuantifiableObservableProperty):
    node_type= None
    hasUnits = qudt.PPM
    hasQuantityKind = quantitykind.Concentration

#attempt to add water, all from diagram, needs checks/incomplete
class HeatExchanger(Equipment):
    node_type= None
    coolingInlet: ChilledWaterInletConnectionPoint
    coolingOutlet: ChilledWaterOutletConnectionPoint
    heatingInlet: ChilledWaterInletConnectionPoint
    heatingOutlet: ChilledWaterOutletConnectionPoint
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
class LoopPressureSensor(Equipment):
    node_type= None #should have just made a sensor class probs
    node_type: URIRef = s223.Sensor
    pressure = QuantifiableObservableProperty  #AnalogIn This results in the turtle file having temperature listed as a property and listed plainly. 
    pressure.hasQuantityKind = quantitykind.StaticPressure #QUDT doesn't seem to have differential pressure quantity kind
    pressure.hasUnits = qudt.IN_H2O
    #check what unit
    hasObservationLocationReturn: Node
    hasObservationLocationSupply: Node
class CoolingPump(Equipment):
    node_type= None #need to check points in Haystack
    waterInlet: ChilledWaterInletConnectionPoint
    waterOutlet: ChilledWaterOutletConnectionPoint

    speedSetpoint = QuantifiableActuatableProperty
    speedSetpoint.hasUnits = qudt.PERCENT
    speedSetpoint.hasQuantityKind = qudt.Speed
    #not sure if it should be qudt.Speed AngularFrequency, something else?
    power = QuantifiableObservableProperty
    power.hasQuantityKind = quantitykind.ElectricPower 
    power.hasUnits = qudt.kiloW
    speedFeedback = QuantifiableObservableProperty #also look up more info on this
    speedFeedback.hasQuantityKind = quantitykind.Frequency
    speedFeedback.hasUnits = qudt.HZ
    vfd_start_stop = ActuatableProperty #Should add categorical (enumerated) to this later 
    airFlow = QuantifiableObservableProperty #need to look up units
    airFlow.hasQuantityKind = quantitykind.VolumeFlowRate
    airFlow.hasUnits = qudt.FT3_PER_MIN #does this have to be dashes????
class CoolingWaterSystem(System): #my Equipment using cool water will be connected to a junction at CWSupply
    node_type= None
    CWSupply: ChilledWaterOutletSystemConnectionPoint
    #not including BTU meters
    from_twgps: ChilledWaterInletSystemConnectionPoint
    to_cooling_towers: ChilledWaterOutletSystemConnectionPoint
    CWReturn: ChilledWaterInletSystemConnectionPoint
    makeUpInlet: ChilledWaterInletSystemConnectionPoint

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        tws_ts = TemperatureSensor(label = self.label + '.TWS_Temp')
        #lets make this connection points
        ex1 = HeatExchanger(label = self.label + '.EX_1')
        self.from_twgps.mapsTo = ex1.coolingInlet
        self>ex1
        cwsupply = Junction(label = 'Chilled Water Supply')
        cwsupply << ex1.coolingOutlet
        self.CWSupply.mapsTo = cwsupply 
        tws_ts % ex1.coolingInlet
        # cws = ChilledWaterConnection(label = self.label + '.CWS')
        # ex1.coolingOutlet>>cws
        cws_ts = TemperatureSensor(label = self.label + '.CWS_Temp')
        self>cws_ts
        # cws_ts % cws
        cws_ts % ex1.coolingOutlet
        #have to use segments and junctions here, this shows different modeling decision between right and left side of Cooling Water Control Schematic
        cwr = Segment(label = self.label + ".CWR")
        makeup = Segment(label = self.label + ".MakeUp")
        j = Junction() #if I should label, I'm not sure what I should do.
        cwr.link_to(j) #connect to or link to?
        makeup.link_to(j) #worried I'm doing this wrong
        mkin = Junction(label = self.label+'MakeUp_Inlet')
        mkin.link_to(makeup)
        self.makeUpInlet.mapsTo = mkin
        cwgp1 = CoolingPump(label = self.label + '.Pump_1')
        cwgp2 = CoolingPump(label = self.label + '.Pump_2')
        self>cwgp1
        self>cwgp2
        j.connect_to(cwgp1.waterInlet)
        j.connect_to(cwgp2.waterInlet)
        pump_out = ChilledWaterConnection(label = self.label + '.Pump_Outputs')
        cwgp1.waterOutlet >> pump_out
        cwgp2.waterOutlet >> pump_out
        EX1_cwr_ts = TemperatureSensor(label = self.label + '.EX-1_CWR_Temp')
        EX1_cwr_ts % pump_out 
        self> EX1_cwr_ts
        ps = LoopPressureSensor(label = self.label + '.CW_Loop_Diff_Pressure')
        ps.hasObservationLocationSupply = ex1.coolingInlet
        ps.hasObservationLocationReturn = cwr
        #not sure how to do loop differential pressure, two measurement locations? 
        pump_out >> ex1.heatingInlet
        EX1_TWR_ts = TemperatureSensor(label = self.label + '.EX-1_TWR_Temp')
        EX1_TWR_ts % ex1.heatingOutlet
        self.to_cooling_towers.mapsTo = ex1.heatingOutlet
        jret = Junction(label = self.label + '.CWR_Inlet')
        jret.link_to(cwr)
        self.CWReturn.mapsTo = jret 
class CoolingTower(Equipment): #should I try to specify type of cooling tower (counterflow I think)
    node_type= None
    waterInlet: ChilledWaterInletConnectionPoint
    waterOutlet: ChilledWaterOutletConnectionPoint
    ssfInlet: ChilledWaterInletConnectionPoint #side stream filter Inlet
    ssfOutlet: ChilledWaterOutletConnectionPoint #side stream filter outlet
    vaporOutlet: AirOutletConnectionPoint #not sure if this is right
    vibrationSwitch = ObservableProperty #not sure what this is
class SSFValve(Equipment):
    node_type= None 
    waterInlet: ChilledWaterInletConnectionPoint
    waterOutlet: ChilledWaterOutletConnectionPoint
    status= ObservableProperty
    openValve= ActuatableProperty
class SSFilter(Equipment): #I need more information on this Filter
    node_type= None
    waterInlet: ChilledWaterInletConnectionPoint
    waterOutlet: ChilledWaterOutletConnectionPoint
class CoolingTowerFan(RTUFan): #has the same points as RTU fan, just different geometry
    node_type= None
class CoolingTowerSystem(System):
    node_type= None #page 56 on visio bill of materials, I am making interesting modeling decisions around the connections and such
    waterInlet: ChilledWaterInletSystemConnectionPoint
    waterOutlet: ChilledWaterOutletSystemConnectionPoint
    def __init__(self, **kwargs: Any) -> None: #Might be misunderstanding schematic, do I need to add more pumps or are those already represented in the cooling watersystem?
        super().__init__(**kwargs)
        ct_dict = {}
        ct_dict[1] = self.ct1 = CoolingTower(label = self.label + '.Cooling_Tower_1')
        ct_dict[2] = self.ct2 = CoolingTower(label = self.label + '.Cooling_Tower_2')
        ct_dict[3] = self.ct3 = CoolingTower(label = self.label + '.Cooling_Tower_3')
        ct_dict[4] = self.ct4 = CoolingTower(label = self.label + '.Cooling_Tower_4')
        jin = Junction(label = self.label + '.CTS_Inlet') #I'm not sure these junction/connections are working right
        jout = Junction(label = self.label + '.CTS_Outlet')
        self.waterInlet.mapsTo = jin
        self.waterOutlet.mapsTo = jout
        for ct in ct_dict:
            fan = CoolingTowerFan(label = ct_dict[ct].label + '.CT_Fan')
            ct_dict[ct].vaporOutlet >> fan.airInlet #do I need to indicate that this system has an outlet point for this vapor
            jout << ct_dict[ct].waterOutlet
            jin >> ct_dict[ct].waterInlet 
            ts = TemperatureSensor(label = ct_dict[ct].label + '.TWS_Temp')
            ts % ct_dict[ct].waterOutlet
class SSFSystem(System): 
    node_type= None#going to be a subsystem, missing overflow. Where does side stream water come from? This system seems to be closed except for cooling towers as middlemen
    SSFEnable: ActuatableProperty #these will be enumerated properties
    SSFPowerStatus: ObservableProperty
    SSFModeStatus: ObservableProperty
    def __init__(self, cts: CoolingTowerSystem, **kwargs: Any) -> None: #not sure it should be allowed
        super().__init__(**kwargs)
        to_ssf = ChilledWaterConnection(label = self.label + '.to_ssf')
        from_ssf = ChilledWaterConnection(label = self.label + '.from_ssf')
        ssf = SSFilter(label = self.label + '.Side_Stream_Filter')
        to_ssf >> ssf.waterInlet
        ssf.waterOutlet >> from_ssf
        ct_dict = {1:cts.ct1, 2:cts.ct2, 3:cts.ct3, 4:cts.ct4}
        for ct in ct_dict:
            vo = SSFValve(label = ct_dict[ct].label + ".SSFValve_to_filter") #if I need to access these valves again this will have to change
            vi = SSFValve(label = ct_dict[ct].label + ".SSFValve_from_filter")
            ct_dict[ct].ssfInlet << vi.waterOutlet
            ct_dict[ct].ssfOutlet >> vo.waterInlet
            vi.waterInlet << from_ssf
            vo.waterOutlet >> to_ssf

class ReturnZone(Zone): #adding CO2 point in instantiation #Could use HVACZone1 but space is not declared as self.space. What is the more streamlined way of doing this?
    node_type= None
    returnAirInlet: AirInletZoneConnectionPoint
    hasDomain = HVAC

class Lighting_Zone(Zone):
    node_type = None
    hasDomain = Lighting

class Area(QuantifiableObservableProperty):
    node_type= None
    hasUnits = qudt.FT2
    hasQuantityKind = quantitykind.Area
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

class Wattage(QuantifiableObservableProperty): 
    node_type= None
    hasQuantityKind = quantitykind.ElectricPower #QUDT doesn't seem to have differential pressure quantity kind
    hasUnits = qudt.W
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

class Light_Fixtures(Equipment):
    node_type= None
    FixtureWattage = Wattage
    FixtureQty = ObservableProperty #This is the type and quantity it seems, can separate this out into more properties later
    LoadType = ObservableProperty 

class Zone_Lighting(System): 
    node_type= None
    TotalWattage = Wattage
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class Illuminance(QuantifiableObservableProperty): 
    node_type= None
    hasQuantityKind = quantitykind.Illuminance #QUDT doesn't seem to have differential pressure quantity kind
    hasUnits = qudt.FC
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

class Daylight_Sensor(Equipment):
    node_type: URIRef = s223.Sensor
    illuminance = Illuminance
    hasObservationLocation: Node

In [34]:
d = System(label = 'd')

In [36]:
dir(d.serves_zone())

AttributeError: 'System' object has no attribute 'serves_zone'